name: 'cydig/compliance@v1'
description: 'Cydig compliance action'
author: 'Omegapoint'

inputs:
  cydigConfigPath:
    description: 'The path to the json-file containing configuration for CyDig'
    required: true
    default: 'Not working'
  PAT-token:
    description: 'Automatic token from Github workflow'
    required: true
    default: 'Not working'
runs:
  using: node20
  main: dist/index.js
