name: Build
run-name: ${{ github.actor }} is testing out github actions


on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: debug root
        run: ls
      - name: debug subfolder
        run: cd src && ls
      - name: Build
        run: npm run build
      - name: 'Run Compliance State'
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cydigConfigPath: ${{ github.workspace }}/src/cydigconfig.json
          github-token: ${{ secrets.MY_GITHUB_PAT}}
