name: Build
run-name: ${{ github.actor }} is testing out github actions
permissions:
  contents: read
  pages: read
  id-token: write
  actions: read
  checks: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: debug root
        run: ls
      - name: debug subfolder
        run: cd src && ls
      - name: Build
        run: npm run build
      - name: 'Run Compliance State'
        uses: ./
        with:
          cydigConfigPath: ${{ github.workspace }}/src/cydigconfig.json
          github-token: ${{ secrets.MY_GITHUB_PAT}}
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
