name: Build
run-name: ${{ github.actor }} is testing out github actions
permissions:
  contents: write
  pages: write
  id-token: write

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node
      uses: actions/setup-node@v3
    - name: Install
      run: npm ci
    - name: Build 
      run: npm run build
    - name: 'Run Compliance State'
      uses: ./
      with:
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    