name: Test
run-name: ${{ github.actor }} is running tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install
        run: npm ci
      - name: Build tests
        run: npm run buildTests
